### ISSUE TITLE
Wrong paths in html

### ISSUE THREAD

**Issue by Vourhey** [RyanHendricks/doxity-simpleton#1]
semantic css link is broken and bundle.js too
But if I change it manually I see blank page. 
What could it be? 
Edit: I'm trying to run it locally

**Comment by RyanHendricks** [comment]
I made two small changes to the readme and config.toml file, the update to the readme being more important since ultimately you would need to run 'yarn' in two directories. Not sure if this edit will help here but I am wondering what version of node are you running when this error is occuring? 

Also, for the broken links and bundlejs, I think the trouble might be running it locally, but try this fix and let me know if it works for local install:
from within the root folder-

npm install http-server
http-server ./docs/

**Comment by Vourhey** [comment]
@RyanHendricks it worked! Thanks. Yes, the problem was with 'yarn' in doxity directory. I'm using node v8.8.1, works fine. 

By the way, here's one improvement I did:

file lib/compile/solc.js line 38

```
var walkSync = function(dir, filelist) {
            var path = path || require('path');
            var fs = fs || require('fs'),
                files = fs.readdirSync(dir);
            filelist = filelist || [];
            files.forEach(function(file) {
                if (fs.statSync(path.join(dir, file)).isDirectory()) {
                    filelist = walkSync(path.join(dir, file), filelist);
                }
                else {
                    filelist.push(path.join(dir, file));
                }
            });
            return filelist;
        };
      src = src.slice(0,-1);
      src = walkSync(src).join(' ');
      console.log(src);
      var exec = 'solc --combined-json abi,asm,ast,bin,bin-runtime,clone-bin,devdoc,interface,opcodes,srcmap,srcmap-runtime,userdoc --allow-paths contracts/, =./contracts/ ' + src;
```

In case contract directory contains subdirs

**Comment by RyanHendricks** [comment]
@Vourhey glad to hear and thank you for that improvement! I am going to try to integrate the doxity dependency files into the main project files over next couple of days and will definitely include this addition. Thanks!

**Comment by Vourhey** [comment]
@RyanHendricks could you help me again? I tested docs locally, but when I push it to github it doesn't work. It can't find bundle.js
https://vourhey.github.io/core/docs/
I checked your repo https://github.com/RyanHendricks/protocol It looks same but mine isn't working. Where did I do mistake? Thanks

**Comment by RyanHendricks** [comment]
It wasn't a mistake on your part but rather additional instructions were needed as well as a few minor tweaks.

Try re-cloning the project (I made a good number of changes) and the directions in the Readme should now lead you to working Github pages. Just be sure to edit the package.json listed as this is key for making the github pages work.

Let me know if you are able to get it up and running and I really do appreciate the feedback :)

**Comment by Vourhey** [comment]
Thanks again! It was a great help!

Yes, I got it up, now everything works. Your readme helped =)

**Comment by RyanHendricks** [comment]
Great to hear! And the difficulties/questions helped me to get the readme to that point haha. Thanks!
